### PR TITLE
Cache bundler gems

### PR DESCRIPTION
**Pull request by Dantemss**
This should make deployment faster and use less memory (so we can actually deploy exchange-dev).

The downside is that it adds 74MB to the repo size.

What do you think?

### CODE REVIEW

**Comment by cnuber** [comment]
We get about 7-10MB/sec download from github to our bastion server, so it'd add like 10-15 seconds max to the pull and probably reduce the deployment by 30-60 seconds.  I consider that a win

**Comment by Dantemss** [comment]
An alternative would be to gitignore this and have the deployment script run `bundle package --all`

**Comment by philschatz** [comment]
:+1: for not wiping the gemfiles on each deploy (as someone w/o fiber hookup to my laptop :smile: )

**Comment by Dantemss** [comment]
Actually @philschatz looks like making the script run `bundle package --all` locally is not really an option because it would require devops to install bundler and everything... so maybe we'll just have to commit the gems to the repos...

**Comment by philschatz** [comment]
Is there no way for bundler to only download the new gems?

**Comment by Dantemss** [comment]
Settings the bundler `--path` to some constant folder in the deployment script would do that.

**Pull request closed without merging**
