### PR TITLE
Make Activities of each type unique for each Task

### PR DESCRIPTION
**Pull request by Dantemss**
- Lock activities after creation
- Add a unique index on task_id
- Updated existing specs

### CODE REVIEW

**Comment by jpslav** [comment]
before un-WIP'd you'll add migrations?

**Comment by Dantemss** [comment]
Hm sure I will add some migrations to re-generate those indices.

**Comment by Dantemss** [comment]
I'm still experimenting though... the real issue still eludes me (why we get a NameError after a transaction retry).

**Comment by Dantemss** [comment]
Since the issue was determined to be in Lev, this PR no longer attempts to address it. Instead I'm just adding the missing uniqueness validation.

**Pull request merged**
